
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-cluster'
    static_configs:
      - targets:
        - 'kafka-node1:7071'
        - 'kafka-node2:7071'
        - 'kafka-node3:7071'
        labels:
          env: 'dev'